const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

// =========================================================================
// 1. MASTER OVERSEAS CLUBS REGISTRY (120+ CLUBS)
// =========================================================================
const OVERSEAS_CLUBS = [
  // --- SWEDEN: SHL (14 Teams) ---
  { id: "cl_se_frolunda", name: "Frölunda HC", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Gothenburg", arena: "Scandinavium", capacity: 12044, rinkSize: "Olympic Rink (30m × 60m)", established: 1938 },
  { id: "cl_se_farjestad", name: "Färjestad BK", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Karlstad", arena: "Löfbergs Arena", capacity: 8250, rinkSize: "Olympic Rink (30m × 60m)", established: 1932 },
  { id: "cl_se_skelleftea", name: "Skellefteå AIK", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Skellefteå", arena: "Skellefteå Kraft Arena", capacity: 5801, rinkSize: "Olympic Rink (30m × 60m)", established: 1921 },
  { id: "cl_se_rogle", name: "Rögle BK", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Ängelholm", arena: "Catena Arena", capacity: 5051, rinkSize: "Olympic Rink (30m × 60m)", established: 1932 },
  { id: "cl_se_lulea", name: "Luleå HF", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Luleå", arena: "Coop Norrbotten Arena", capacity: 6150, rinkSize: "Olympic Rink (30m × 60m)", established: 1977 },
  { id: "cl_se_hv71", name: "HV71", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Jönköping", arena: "Husqvarna Garden", capacity: 7000, rinkSize: "Olympic Rink (30m × 60m)", established: 1971 },
  { id: "cl_se_brynas", name: "Brynäs IF", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Gävle", arena: "Monitor ERP Arena", capacity: 7909, rinkSize: "Olympic Rink (30m × 60m)", established: 1912 },
  { id: "cl_se_linkoping", name: "Linköping HC", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Linköping", arena: "Saab Arena", capacity: 8500, rinkSize: "Olympic Rink (30m × 60m)", established: 1976 },
  { id: "cl_se_orebro", name: "Örebro HK", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Örebro", arena: "Behrn Arena", capacity: 5500, rinkSize: "Olympic Rink (30m × 60m)", established: 1990 },
  { id: "cl_se_timra", name: "Timrå IK", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Timrå", arena: "SCA Arena", capacity: 6000, rinkSize: "Olympic Rink (30m × 60m)", established: 1928 },
  { id: "cl_se_vaxjo", name: "Växjö Lakers", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Växjö", arena: "Vida Arena", capacity: 5750, rinkSize: "Olympic Rink (30m × 60m)", established: 1997 },
  { id: "cl_se_leksand", name: "Leksands IF", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Leksand", arena: "Tegera Arena", capacity: 7650, rinkSize: "Olympic Rink (30m × 60m)", established: 1919 },
  { id: "cl_se_malmo", name: "Malmö Redhawks", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Malmö", arena: "Malmö Arena", capacity: 12600, rinkSize: "Olympic Rink (30m × 60m)", established: 1972 },
  { id: "cl_se_modo", name: "MoDo Hockey", country: "Sweden", flag: "🇸🇪", league: "SHL (Swedish Hockey League)", tier: "Tier 1 Pro", city: "Örnsköldsvik", arena: "Hägglunds Arena", capacity: 7115, rinkSize: "Olympic Rink (30m × 60m)", established: 1921 },

  // --- SWEDEN: HockeyAllsvenskan (Tier 2 Pro / Top Feeder) ---
  { id: "cl_se_djurgarden", name: "Djurgårdens IF", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Stockholm", arena: "Hovet", capacity: 8094, rinkSize: "Olympic Rink (30m × 60m)", established: 1891 },
  { id: "cl_se_aik", name: "AIK Ishockey", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Stockholm", arena: "Hovet", capacity: 8094, rinkSize: "Olympic Rink (30m × 60m)", established: 1921 },
  { id: "cl_se_sodertalje", name: "Södertälje SK", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Södertälje", arena: "Scaniarinken", capacity: 6200, rinkSize: "Olympic Rink (30m × 60m)", established: 1902 },
  { id: "cl_se_bjorkloven", name: "IF Björklöven", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Umeå", arena: "Winpos Arena", capacity: 5400, rinkSize: "Olympic Rink (30m × 60m)", established: 1970 },
  { id: "cl_se_mora", name: "Mora IK", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Mora", arena: "Smidjegrav Arena", capacity: 4500, rinkSize: "Olympic Rink (30m × 60m)", established: 1935 },
  { id: "cl_se_karlskoga", name: "BIK Karlskoga", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Karlskoga", arena: "Nobelhallen", capacity: 5400, rinkSize: "Olympic Rink (30m × 60m)", established: 1943 },
  { id: "cl_se_ostersund", name: "Östersunds IK", country: "Sweden", flag: "🇸🇪", league: "HockeyAllsvenskan", tier: "Tier 2 Pro", city: "Östersund", arena: "Östersund Arena", capacity: 2700, rinkSize: "Olympic Rink (30m × 60m)", established: 1965 },

  // --- FINLAND: Liiga (16 Teams) ---
  { id: "cl_fi_tappara", name: "Tappara", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Tampere", arena: "Nokia Arena", capacity: 13455, rinkSize: "Olympic Rink (30m × 60m)", established: 1955 },
  { id: "cl_fi_ilves", name: "Ilves", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Tampere", arena: "Nokia Arena", capacity: 13455, rinkSize: "Olympic Rink (30m × 60m)", established: 1931 },
  { id: "cl_fi_hifk", name: "HIFK", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Helsinki", arena: "Helsinki Ice Hall", capacity: 8200, rinkSize: "Olympic Rink (30m × 60m)", established: 1897 },
  { id: "cl_fi_karpat", name: "Kärpät", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Oulu", arena: "Oulun Energia Areena", capacity: 6614, rinkSize: "Olympic Rink (30m × 60m)", established: 1946 },
  { id: "cl_fi_tps", name: "TPS Turku", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Turku", arena: "Gatorade Center", capacity: 10500, rinkSize: "Olympic Rink (30m × 60m)", established: 1922 },
  { id: "cl_fi_lukko", name: "Lukko", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Rauma", arena: "Kivikylän Areena", capacity: 4500, rinkSize: "Olympic Rink (30m × 60m)", established: 1936 },
  { id: "cl_fi_pelicans", name: "Pelicans", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Lahti", arena: "Isku Areena", capacity: 4403, rinkSize: "Olympic Rink (30m × 60m)", established: 1996 },
  { id: "cl_fi_kalpa", name: "KalPa", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Kuopio", arena: "Olvi Areena", capacity: 5300, rinkSize: "Olympic Rink (30m × 60m)", established: 1929 },
  { id: "cl_fi_jukurit", name: "Jukurit", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Mikkeli", arena: "Ikioma Areena", capacity: 4200, rinkSize: "Olympic Rink (30m × 60m)", established: 1970 },
  { id: "cl_fi_assat", name: "Ässät", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Pori", arena: "Enersense Areena", capacity: 6150, rinkSize: "Olympic Rink (30m × 60m)", established: 1967 },
  { id: "cl_fi_kookoo", name: "KooKoo", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Kouvola", arena: "Lumon Areena", capacity: 5950, rinkSize: "Olympic Rink (30m × 60m)", established: 1965 },
  { id: "cl_fi_sport", name: "Vaasan Sport", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Vaasa", arena: "Vaasan Sähkö Areena", capacity: 5185, rinkSize: "Olympic Rink (30m × 60m)", established: 1939 },
  { id: "cl_fi_hpk", name: "HPK", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Hämeenlinna", arena: "Pohjantähti Areena", capacity: 5360, rinkSize: "Olympic Rink (30m × 60m)", established: 1929 },
  { id: "cl_fi_jyp", name: "JYP Jyväskylä", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Jyväskylä", arena: "LähiTapiola Areena", capacity: 4437, rinkSize: "Olympic Rink (30m × 60m)", established: 1977 },
  { id: "cl_fi_saipa", name: "SaiPa", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Lappeenranta", arena: "Kisapuiston jäähalli", capacity: 4820, rinkSize: "Olympic Rink (30m × 60m)", established: 1948 },
  { id: "cl_fi_kiekko_espoo", name: "Kiekko-Espoo", country: "Finland", flag: "🇫🇮", league: "Liiga", tier: "Tier 1 Pro", city: "Espoo", arena: "Espoo Metro Areena", capacity: 6982, rinkSize: "Olympic Rink (30m × 60m)", established: 1984 },

  // --- FINLAND: Mestis (Feeder) ---
  { id: "cl_fi_jokerit", name: "Jokerit Helsinki", country: "Finland", flag: "🇫🇮", league: "Mestis", tier: "Tier 2 Pro", city: "Helsinki", arena: "Helsinki Ice Hall", capacity: 8200, rinkSize: "Olympic Rink (30m × 60m)", established: 1967 },
  { id: "cl_fi_tuto", name: "TUTO Hockey", country: "Finland", flag: "🇫🇮", league: "Mestis", tier: "Tier 2 Pro", city: "Turku", arena: "Rajupaja Areena", capacity: 3000, rinkSize: "Olympic Rink (30m × 60m)", established: 1929 },
  { id: "cl_fi_ipk", name: "IPK Iisalmi", country: "Finland", flag: "🇫🇮", league: "Mestis", tier: "Tier 2 Pro", city: "Iisalmi", arena: "Kankaan jäähalli", capacity: 1500, rinkSize: "Olympic Rink (30m × 60m)", established: 1966 },

  // --- SWITZERLAND: National League (14 Teams) ---
  { id: "cl_ch_zsc_lions", name: "ZSC Lions", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Zürich", arena: "Swiss Life Arena", capacity: 12000, rinkSize: "Olympic Rink (30m × 60m)", established: 1930 },
  { id: "cl_ch_ev_zug", name: "EV Zug", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Zug", arena: "Bossard Arena", capacity: 7200, rinkSize: "Olympic Rink (30m × 60m)", established: 1967 },
  { id: "cl_ch_sc_bern", name: "SC Bern", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Bern", arena: "PostFinance Arena", capacity: 17031, rinkSize: "Olympic Rink (30m × 60m)", established: 1931 },
  { id: "cl_ch_hc_davos", name: "HC Davos", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Davos", arena: "Eisstadion Davos", capacity: 7080, rinkSize: "Olympic Rink (30m × 60m)", established: 1921 },
  { id: "cl_ch_geneve", name: "Genève-Servette HC", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Geneva", arena: "Patinoire des Vernets", capacity: 7135, rinkSize: "Olympic Rink (30m × 60m)", established: 1905 },
  { id: "cl_ch_lugano", name: "HC Lugano", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Lugano", arena: "Cornèr Arena", capacity: 7200, rinkSize: "Olympic Rink (30m × 60m)", established: 1941 },
  { id: "cl_ch_fribourg", name: "Fribourg-Gottéron", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Fribourg", arena: "BCF Arena", capacity: 9009, rinkSize: "Olympic Rink (30m × 60m)", established: 1937 },
  { id: "cl_ch_lausanne", name: "Lausanne HC", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Lausanne", arena: "Vaudoise aréna", capacity: 9600, rinkSize: "Olympic Rink (30m × 60m)", established: 1922 },
  { id: "cl_ch_biel", name: "EHC Biel-Bienne", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Biel/Bienne", arena: "Tissot Arena", capacity: 6521, rinkSize: "Olympic Rink (30m × 60m)", established: 1939 },
  { id: "cl_ch_ambri", name: "HC Ambrì-Piotta", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Ambrì", arena: "Gottardo Arena", capacity: 6775, rinkSize: "Olympic Rink (30m × 60m)", established: 1937 },
  { id: "cl_ch_rapperswil", name: "SC Rapperswil-Jona Lakers", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Rapperswil", arena: "St. Galler Kantonalbank Arena", capacity: 6100, rinkSize: "Olympic Rink (30m × 60m)", established: 1945 },
  { id: "cl_ch_kloten", name: "EHC Kloten", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Kloten", arena: "Stimo Arena", capacity: 7624, rinkSize: "Olympic Rink (30m × 60m)", established: 1934 },
  { id: "cl_ch_langnau", name: "SCL Tigers", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Langnau im Emmental", arena: "ILFISHALLE", capacity: 6000, rinkSize: "Olympic Rink (30m × 60m)", established: 1946 },
  { id: "cl_ch_ajoie", name: "HC Ajoie", country: "Switzerland", flag: "🇨🇭", league: "National League (NL)", tier: "Tier 1 Pro", city: "Porrentruy", arena: "Raiffeisen Arena", capacity: 5178, rinkSize: "Olympic Rink (30m × 60m)", established: 1973 },

  // --- GERMANY: DEL (Deutsche Eishockey Liga) ---
  { id: "cl_de_eisbaren", name: "Eisbären Berlin", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Berlin", arena: "Uber Arena", capacity: 14200, rinkSize: "Olympic Rink (30m × 60m)", established: 1954 },
  { id: "cl_de_munchen", name: "EHC Red Bull München", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Munich", arena: "SAP Garden", capacity: 10796, rinkSize: "Olympic Rink (30m × 60m)", established: 1998 },
  { id: "cl_de_mannheim", name: "Adler Mannheim", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Mannheim", arena: "SAP Arena", capacity: 13600, rinkSize: "Olympic Rink (30m × 60m)", established: 1938 },
  { id: "cl_de_kolner", name: "Kölner Haie", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Cologne", arena: "LANXESS arena", capacity: 18600, rinkSize: "Olympic Rink (30m × 60m)", established: 1972 },
  { id: "cl_de_ingolstadt", name: "ERC Ingolstadt", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Ingolstadt", arena: "Saturn Arena", capacity: 4815, rinkSize: "Olympic Rink (30m × 60m)", established: 1964 },
  { id: "cl_de_straubing", name: "Straubing Tigers", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Straubing", arena: "Eisstadion am Pulverturm", capacity: 5635, rinkSize: "Olympic Rink (30m × 60m)", established: 1941 },
  { id: "cl_de_bremerhaven", name: "Fischtown Pinguins", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Bremerhaven", arena: "Eisarena Bremerhaven", capacity: 4647, rinkSize: "Olympic Rink (30m × 60m)", established: 1974 },
  { id: "cl_de_nurnberg", name: "Nürnberg Ice Tigers", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Nuremberg", arena: "ARENA NÜRNBERGER Versicherung", capacity: 7672, rinkSize: "Olympic Rink (30m × 60m)", established: 1980 },
  { id: "cl_de_dusseldorf", name: "Düsseldorfer EG", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Düsseldorf", arena: "PSD BANK DOME", capacity: 13102, rinkSize: "Olympic Rink (30m × 60m)", established: 1935 },
  { id: "cl_de_wolfsburg", name: "Grizzlys Wolfsburg", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Wolfsburg", arena: "Eis Arena Wolfsburg", capacity: 4503, rinkSize: "Olympic Rink (30m × 60m)", established: 1975 },
  { id: "cl_de_schwenningen", name: "Schwenninger Wild Wings", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Villingen-Schwenningen", arena: "Helios Arena", capacity: 6125, rinkSize: "Olympic Rink (30m × 60m)", established: 1904 },
  { id: "cl_de_iserlohn", name: "Iserlohn Roosters", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Iserlohn", arena: "Balver Zinn Arena", capacity: 4967, rinkSize: "Olympic Rink (30m × 60m)", established: 1959 },
  { id: "cl_de_augsburg", name: "Augsburger Panther", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Augsburg", arena: "Curt-Frenzel-Stadion", capacity: 6179, rinkSize: "Olympic Rink (30m × 60m)", established: 1878 },
  { id: "cl_de_frankfurt", name: "Löwen Frankfurt", country: "Germany", flag: "🇩🇪", league: "DEL (Deutsche Eishockey Liga)", tier: "Tier 1 Pro", city: "Frankfurt", arena: "Eissporthalle Frankfurt", capacity: 6990, rinkSize: "Olympic Rink (30m × 60m)", established: 1991 },

  // --- CZECHIA: Tipsport Extraliga (14 Teams) ---
  { id: "cl_cz_sparta", name: "HC Sparta Praha", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Prague", arena: "O2 Arena Prague", capacity: 17383, rinkSize: "Olympic Rink (30m × 60m)", established: 1903 },
  { id: "cl_cz_pardubice", name: "HC Dynamo Pardubice", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Pardubice", arena: "Enteria arena", capacity: 10194, rinkSize: "Olympic Rink (30m × 60m)", established: 1923 },
  { id: "cl_cz_trinec", name: "HC Oceláři Třinec", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Třinec", arena: "Werk Arena", capacity: 5400, rinkSize: "Olympic Rink (30m × 60m)", established: 1929 },
  { id: "cl_cz_kometa", name: "HC Kometa Brno", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Brno", arena: "Winning Group Arena", capacity: 7700, rinkSize: "Olympic Rink (30m × 60m)", established: 1953 },
  { id: "cl_cz_liberec", name: "Bílí Tygři Liberec", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Liberec", arena: "Home Credit Arena", capacity: 7500, rinkSize: "Olympic Rink (30m × 60m)", established: 1956 },
  { id: "cl_cz_plzen", name: "HC Škoda Plzeň", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Plzeň", arena: "LOGSPEED CZ Aréna", capacity: 7536, rinkSize: "Olympic Rink (30m × 60m)", established: 1929 },
  { id: "cl_cz_karlovy_vary", name: "HC Energie Karlovy Vary", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Karlovy Vary", arena: "KV Arena", capacity: 5874, rinkSize: "Olympic Rink (30m × 60m)", established: 1932 },
  { id: "cl_cz_vitkovice", name: "HC Vítkovice Ridera", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Ostrava", arena: "OSTRAVAR Aréna", capacity: 9833, rinkSize: "Olympic Rink (30m × 60m)", established: 1928 },
  { id: "cl_cz_hradec", name: "Mountfield HK", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Hradec Králové", arena: "ČPP Aréna", capacity: 6890, rinkSize: "Olympic Rink (30m × 60m)", established: 1925 },
  { id: "cl_cz_litvinov", name: "HC Verva Litvínov", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Litvínov", arena: "Zimní stadion Ivana Hlinky", capacity: 5944, rinkSize: "Olympic Rink (30m × 60m)", established: 1945 },
  { id: "cl_cz_boleslav", name: "BK Mladá Boleslav", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Mladá Boleslav", arena: "ŠKO-ENERGO Aréna", capacity: 4200, rinkSize: "Olympic Rink (30m × 60m)", established: 1908 },
  { id: "cl_cz_olomouc", name: "HC Olomouc", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Olomouc", arena: "Zimní stadion Olomouc", capacity: 5500, rinkSize: "Olympic Rink (30m × 60m)", established: 1955 },
  { id: "cl_cz_kladno", name: "Rytíři Kladno", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "Kladno", arena: "ČEZ Stadion Kladno", capacity: 5200, rinkSize: "Olympic Rink (30m × 60m)", established: 1924 },
  { id: "cl_cz_motor", name: "Banes Motor České Budějovice", country: "Czech Republic", flag: "🇨🇿", league: "Tipsport Extraliga", tier: "Tier 1 Pro", city: "České Budějovice", arena: "Budvar Aréna", capacity: 6421, rinkSize: "Olympic Rink (30m × 60m)", established: 1928 },

  // --- AUSTRIA & CENTRAL EUROPE: ICEHL (win2day ICE Hockey League) ---
  { id: "cl_at_salzburg", name: "EC Red Bull Salzburg", country: "Austria", flag: "🇦🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Salzburg", arena: "Eisarena Salzburg", capacity: 3400, rinkSize: "Olympic Rink (30m × 60m)", established: 1977 },
  { id: "cl_at_klagenfurt", name: "EC-KAC Klagenfurt", country: "Austria", flag: "🇦🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Klagenfurt", arena: "Heidi Horten-Arena", capacity: 4390, rinkSize: "Olympic Rink (30m × 60m)", established: 1909 },
  { id: "cl_at_vienna", name: "Vienna Capitals", country: "Austria", flag: "🇦🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Vienna", arena: "Steffl Arena", capacity: 7022, rinkSize: "Olympic Rink (30m × 60m)", established: 2001 },
  { id: "cl_at_linz", name: "Steinbach Black Wings Linz", country: "Austria", flag: "🇦🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Linz", arena: "Linz AG Eisarena", capacity: 4863, rinkSize: "Olympic Rink (30m × 60m)", established: 1992 },
  { id: "cl_hu_fehervar", name: "Hydro Fehérvár AV19", country: "Hungary", flag: "🇭🇺", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Székesfehérvár", arena: "Alba Aréna", capacity: 6000, rinkSize: "Olympic Rink (30m × 60m)", established: 1960 },
  { id: "cl_it_bolzano", name: "HCB Südtirol Alperia (Bolzano)", country: "Italy", flag: "🇮🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Bolzano", arena: "Sparkasse Arena", capacity: 7200, rinkSize: "Olympic Rink (30m × 60m)", established: 1933 },
  { id: "cl_it_pustertal", name: "HC Pustertal Wölfe", country: "Italy", flag: "🇮🇹", league: "ICEHL (win2day ICE Hockey League)", tier: "Tier 1 Pro", city: "Bruneck", arena: "Intercable Arena", capacity: 3100, rinkSize: "Olympic Rink (30m × 60m)", established: 1954 },

  // --- NORWAY: EliteHockey Ligaen ---
  { id: "cl_no_valerenga", name: "Vålerenga Ishockey", country: "Norway", flag: "🇳🇴", league: "EliteHockey Ligaen", tier: "Tier 1 Pro", city: "Oslo", arena: "Jordal Amfi", capacity: 5300, rinkSize: "Olympic Rink (30m × 60m)", established: 1913 },
  { id: "cl_no_stavanger", name: "Stavanger Oilers", country: "Norway", flag: "🇳🇴", league: "EliteHockey Ligaen", tier: "Tier 1 Pro", city: "Stavanger", arena: "DNB Arena", capacity: 4250, rinkSize: "Olympic Rink (30m × 60m)", established: 2000 },
  { id: "cl_no_storhamar", name: "Storhamar Hockey", country: "Norway", flag: "🇳🇴", league: "EliteHockey Ligaen", tier: "Tier 1 Pro", city: "Hamar", arena: "CC Amfi", capacity: 7500, rinkSize: "Olympic Rink (30m × 60m)", established: 1957 },
  { id: "cl_no_frisk", name: "Frisk Asker", country: "Norway", flag: "🇳🇴", league: "EliteHockey Ligaen", tier: "Tier 1 Pro", city: "Asker", arena: "Varner Arena", capacity: 3800, rinkSize: "Olympic Rink (30m × 60m)", established: 1922 },

  // --- UNITED KINGDOM: EIHL (Elite Ice Hockey League) ---
  { id: "cl_uk_belfast", name: "Belfast Giants", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Belfast", arena: "SSE Arena Belfast", capacity: 8700, rinkSize: "Olympic Rink (30m × 60m)", established: 2000 },
  { id: "cl_uk_sheffield", name: "Sheffield Steelers", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Sheffield", arena: "Utilita Arena Sheffield", capacity: 9300, rinkSize: "Olympic Rink (30m × 60m)", established: 1991 },
  { id: "cl_uk_cardiff", name: "Cardiff Devils", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Cardiff", arena: "Vindico Arena", capacity: 3088, rinkSize: "Olympic Rink (30m × 60m)", established: 1986 },
  { id: "cl_uk_nottingham", name: "Nottingham Panthers", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Nottingham", arena: "Motorpoint Arena Nottingham", capacity: 7500, rinkSize: "Olympic Rink (30m × 60m)", established: 1946 },
  { id: "cl_uk_glasgow", name: "Glasgow Clan", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Glasgow", arena: "Braehead Arena", capacity: 4000, rinkSize: "Olympic Rink (30m × 60m)", established: 2010 },
  { id: "cl_uk_dundee", name: "Dundee Stars", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Dundee", arena: "Dundee Ice Arena", capacity: 2300, rinkSize: "Olympic Rink (30m × 60m)", established: 2001 },
  { id: "cl_uk_coventry", name: "Coventry Blaze", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Coventry", arena: "Skydome Arena", capacity: 3000, rinkSize: "Olympic Rink (30m × 60m)", established: 2000 },
  { id: "cl_uk_fife", name: "Fife Flyers", country: "United Kingdom", flag: "🇬🇧", league: "EIHL (Elite Ice Hockey League)", tier: "Tier 1 Pro", city: "Kirkcaldy", arena: "Fife Ice Arena", capacity: 3525, rinkSize: "Olympic Rink (30m × 60m)", established: 1938 },

  // --- ASIA: Asia League Ice Hockey ---
  { id: "cl_jp_red_eagles", name: "Red Eagles Hokkaido", country: "Japan", flag: "🇯🇵", league: "Asia League Ice Hockey", tier: "Tier 1 Pro", city: "Tomakomai", arena: "Hakucho Oji Ice Arena", capacity: 3015, rinkSize: "Olympic Rink (30m × 60m)", established: 1925 },
  { id: "cl_kr_anyang", name: "HL Anyang", country: "South Korea", flag: "🇰🇷", league: "Asia League Ice Hockey", tier: "Tier 1 Pro", city: "Anyang", arena: "Anyang Ice Rink", capacity: 1709, rinkSize: "Olympic Rink (30m × 60m)", established: 1994 },
  { id: "cl_jp_ice_bucks", name: "Nikko Ice Bucks", country: "Japan", flag: "🇯🇵", league: "Asia League Ice Hockey", tier: "Tier 1 Pro", city: "Nikko", arena: "Nikko Kirifuri Ice Arena", capacity: 2000, rinkSize: "Olympic Rink (30m × 60m)", established: 1999 },
  { id: "cl_jp_free_blades", name: "Tohoku Free Blades", country: "Japan", flag: "🇯🇵", league: "Asia League Ice Hockey", tier: "Tier 1 Pro", city: "Hachinohe", arena: "Flat Hachinohe", capacity: 3500, rinkSize: "Olympic Rink (30m × 60m)", established: 2008 },
  { id: "cl_jp_yokohama", name: "Yokohama Grits", country: "Japan", flag: "🇯🇵", league: "Asia League Ice Hockey", tier: "Tier 1 Pro", city: "Yokohama", arena: "KOSÉ Shin-Yokohama Skate Center", capacity: 2500, rinkSize: "Olympic Rink (30m × 60m)", established: 2019 },

  // --- AUSTRALIA: AIHL (Australian Ice Hockey League) ---
  { id: "cl_au_melbourne_ice", name: "Melbourne Ice", country: "Australia", flag: "🇦🇺", league: "AIHL (Australian Ice Hockey League)", tier: "Tier 1 Pro", city: "Melbourne", arena: "O'Brien Icehouse", capacity: 2500, rinkSize: "Olympic Rink (30m × 60m)", established: 2002 },
  { id: "cl_au_sydney_bears", name: "Sydney Bears", country: "Australia", flag: "🇦🇺", league: "AIHL (Australian Ice Hockey League)", tier: "Tier 1 Pro", city: "Sydney", arena: "Macquarie Ice Rink", capacity: 2000, rinkSize: "Olympic Rink (30m × 60m)", established: 1982 },
  { id: "cl_au_newcastle", name: "Newcastle Northstars", country: "Australia", flag: "🇦🇺", league: "AIHL (Australian Ice Hockey League)", tier: "Tier 1 Pro", city: "Newcastle", arena: "Hunter Ice Skating Stadium", capacity: 1000, rinkSize: "Olympic Rink (30m × 60m)", established: 2002 },
  { id: "cl_au_canberra", name: "Canberra Brave", country: "Australia", flag: "🇦🇺", league: "AIHL (Australian Ice Hockey League)", tier: "Tier 1 Pro", city: "Canberra", arena: "Phillip Swimming & Ice Skating Centre", capacity: 1000, rinkSize: "Olympic Rink (30m × 60m)", established: 2014 },
  { id: "cl_au_mustangs", name: "Melbourne Mustangs", country: "Australia", flag: "🇦🇺", league: "AIHL (Australian Ice Hockey League)", tier: "Tier 1 Pro", city: "Melbourne", arena: "O'Brien Icehouse", capacity: 2500, rinkSize: "Olympic Rink (30m × 60m)", established: 2010 },

  // --- EUROPE / KHL PRO CLUBS (Non-NHL Affiliate Clubs) ---
  { id: "cl_ru_ska", name: "SKA Saint Petersburg", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Saint Petersburg", arena: "SKA Arena", capacity: 21542, rinkSize: "NHL Standard (26m × 60m)", established: 1946 },
  { id: "cl_ru_cska", name: "CSKA Moscow", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Moscow", arena: "CSKA Arena", capacity: 12100, rinkSize: "NHL Standard (26m × 60m)", established: 1946 },
  { id: "cl_ru_lokomotiv", name: "Lokomotiv Yaroslavl", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Yaroslavl", arena: "Arena 2000", capacity: 9070, rinkSize: "NHL Standard (26m × 60m)", established: 1959 },
  { id: "cl_ru_torpedo", name: "Torpedo Nizhny Novgorod", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Nizhny Novgorod", arena: "Nagorny Arena", capacity: 5500, rinkSize: "NHL Standard (26m × 60m)", established: 1946 },
  { id: "cl_ru_metallurg", name: "Metallurg Magnitogorsk", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Magnitogorsk", arena: "Arena Metallurg", capacity: 7700, rinkSize: "NHL Standard (26m × 60m)", established: 1955 },
  { id: "cl_ru_avangard", name: "Avangard Omsk", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Omsk", arena: "G-Drive Arena", capacity: 12011, rinkSize: "NHL Standard (26m × 60m)", established: 1950 },
  { id: "cl_ru_dynamo", name: "Dynamo Moscow", country: "Russia", flag: "🇷🇺", league: "KHL", tier: "Tier 1 Pro", city: "Moscow", arena: "VTB Arena", capacity: 10495, rinkSize: "NHL Standard (26m × 60m)", established: 1946 }
];

// Write updated static/js/overseas_clubs_database.js
const clubsJsContent = `/**
 * DraftLineup.com - Master Overseas Hockey Clubs Database
 * Total Verified Overseas Clubs: ${OVERSEAS_CLUBS.length}
 */

(function(window) {
  'use strict';
  window.DRAFTLINEUP_OVERSEAS_CLUBS = ${JSON.stringify(OVERSEAS_CLUBS, null, 2)};
})(typeof window !== 'undefined' ? window : global);
`;

fs.writeFileSync(path.join(rootDir, 'static', 'js', 'overseas_clubs_database.js'), clubsJsContent, 'utf8');
console.log(`✓ Updated overseas_clubs_database.js with ${OVERSEAS_CLUBS.length} international clubs.`);

// =========================================================================
// 2. OVERSEAS PLAYERS & NHL-LOAN PROSPECTS REGISTRY
// =========================================================================
const OVERSEAS_PROSPECTS = [
  // Sweden (SHL & Allsvenskan)
  {
    id: "ovs_001",
    entity_type: "player",
    name: "Axel Sandin Pellikka",
    num: 26,
    pos: "D",
    role_title: "Offensive Defenseman",
    team: "Skellefteå AIK",
    institution: "Skellefteå AIK",
    league: "SHL (Swedish Hockey League)",
    conference: "Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 71,
    height_str: "5'11\"",
    weight_lbs: 180,
    hometown: "Gällivare, Sweden",
    date_of_birth: "2005-01-23",
    previous_team: "Skellefteå AIK J20",
    draft_status: "Detroit (2023, 17th)",
    country: "SWE",
    composite_score: 95.8,
    avatar_gradient: "from-red-600 to-amber-700",
    notes: "Elite puck-moving defenseman in the SHL. Salming Trophy winner. Outstanding transition play and offensive blue-line deception.",
    combine: { flying_30m_sec: 3.42, broad_jump_in: 118, pro_agility_5_10_5_sec: 4.05, grip_strength_lbs: 168, rotational_medball_mph: 52.0 },
    micro_kpis: { controlled_entry_pct: 92.5, controlled_exit_pct: 95.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 89.0, shoulder_scans_per_possession: 8.2, wall_battle_win_pct: 88.0 },
    skill_rubric: { edges: 96, puck_skills: 95, shooting: 91, hockey_iq: 97, contact: 82, d_zone: 88, transition: 98, goalie: 0 }
  },
  {
    id: "ovs_002",
    entity_type: "player",
    name: "Michael Brandsegg-Nygård",
    num: 28,
    pos: "F",
    role_title: "Right Wing",
    team: "Skellefteå AIK",
    institution: "Skellefteå AIK",
    league: "SHL (Swedish Hockey League)",
    conference: "Norway / Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 73,
    height_str: "6'1\"",
    weight_lbs: 207,
    hometown: "Oslo, Norway",
    date_of_birth: "2005-10-05",
    previous_team: "Mora IK (HockeyAllsvenskan)",
    draft_status: "Detroit (2024, 15th)",
    country: "NOR",
    composite_score: 94.6,
    avatar_gradient: "from-blue-600 to-red-700",
    notes: "Historical first-round draft pick from Norway. Powerful pro shot, physical forechecking presence, and defensive commitment.",
    combine: { flying_30m_sec: 3.46, broad_jump_in: 115, pro_agility_5_10_5_sec: 4.12, grip_strength_lbs: 178, rotational_medball_mph: 54.0 },
    micro_kpis: { controlled_entry_pct: 88.0, controlled_exit_pct: 89.5, faceoff_win_pct: 0, high_danger_pass_comp_pct: 84.0, shoulder_scans_per_possession: 6.9, wall_battle_win_pct: 94.0 },
    skill_rubric: { edges: 91, puck_skills: 90, shooting: 96, hockey_iq: 92, contact: 95, d_zone: 91, transition: 90, goalie: 0 }
  },
  {
    id: "ovs_003",
    entity_type: "player",
    name: "David Edstrom",
    num: 22,
    pos: "C",
    role_title: "Two-Way Center",
    team: "Frölunda HC",
    institution: "Frölunda HC",
    league: "SHL (Swedish Hockey League)",
    conference: "Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 75,
    height_str: "6'3\"",
    weight_lbs: 192,
    hometown: "Gothenburg, Sweden",
    date_of_birth: "2005-02-18",
    previous_team: "Frölunda HC J20",
    draft_status: "Nashville (2023, 32nd)",
    country: "SWE",
    composite_score: 93.8,
    avatar_gradient: "from-emerald-700 to-red-800",
    notes: "Prototypical 200-foot center with great size, play-driving instincts, and puck protection down low in the offensive zone.",
    combine: { flying_30m_sec: 3.52, broad_jump_in: 112, pro_agility_5_10_5_sec: 4.18, grip_strength_lbs: 172, rotational_medball_mph: 51.5 },
    micro_kpis: { controlled_entry_pct: 86.0, controlled_exit_pct: 91.0, faceoff_win_pct: 57.5, high_danger_pass_comp_pct: 88.0, shoulder_scans_per_possession: 7.5, wall_battle_win_pct: 91.0 },
    skill_rubric: { edges: 90, puck_skills: 92, shooting: 88, hockey_iq: 95, contact: 90, d_zone: 94, transition: 91, goalie: 0 }
  },
  {
    id: "ovs_004",
    entity_type: "player",
    name: "Stian Solberg",
    num: 88,
    pos: "D",
    role_title: "Physical Shutdown Defenseman",
    team: "Färjestad BK",
    institution: "Färjestad BK",
    league: "SHL (Swedish Hockey League)",
    conference: "Norway / Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 74,
    height_str: "6'2\"",
    weight_lbs: 205,
    hometown: "Oslo, Norway",
    date_of_birth: "2005-12-29",
    previous_team: "Vålerenga Ishockey",
    draft_status: "Anaheim (2024, 23rd)",
    country: "NOR",
    composite_score: 93.2,
    avatar_gradient: "from-emerald-800 to-amber-600",
    notes: "Ferocious open-ice hitter with heavy physical presence and surprisingly nimble backwards skating mobility.",
    combine: { flying_30m_sec: 3.49, broad_jump_in: 116, pro_agility_5_10_5_sec: 4.10, grip_strength_lbs: 185, rotational_medball_mph: 55.0 },
    micro_kpis: { controlled_entry_pct: 82.0, controlled_exit_pct: 90.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 80.0, shoulder_scans_per_possession: 6.8, wall_battle_win_pct: 96.5 },
    skill_rubric: { edges: 92, puck_skills: 87, shooting: 86, hockey_iq: 90, contact: 99, d_zone: 95, transition: 89, goalie: 0 }
  },
  {
    id: "ovs_005",
    entity_type: "player",
    name: "Leo Sahlin Wallenius",
    num: 4,
    pos: "D",
    role_title: "Two-Way Defenseman",
    team: "Växjö Lakers",
    institution: "Växjö Lakers",
    league: "SHL (Swedish Hockey League)",
    conference: "Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 183,
    hometown: "Skövde, Sweden",
    date_of_birth: "2006-04-10",
    previous_team: "Växjö Lakers J20",
    draft_status: "San Jose (2024, 53rd)",
    country: "SWE",
    composite_score: 91.8,
    avatar_gradient: "from-teal-600 to-cyan-800",
    notes: "Silky 4-way skating defenseman with high spatial awareness, breakout composure, and defensive gap control.",
    combine: { flying_30m_sec: 3.44, broad_jump_in: 114, pro_agility_5_10_5_sec: 4.08, grip_strength_lbs: 165, rotational_medball_mph: 50.5 },
    micro_kpis: { controlled_entry_pct: 87.0, controlled_exit_pct: 94.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 86.0, shoulder_scans_per_possession: 7.9, wall_battle_win_pct: 87.0 },
    skill_rubric: { edges: 95, puck_skills: 90, shooting: 85, hockey_iq: 93, contact: 85, d_zone: 90, transition: 95, goalie: 0 }
  },

  // Finland (Liiga)
  {
    id: "ovs_006",
    entity_type: "player",
    name: "Konsta Helenius",
    num: 19,
    pos: "C",
    role_title: "Playmaking Center",
    team: "Tappara",
    institution: "Tappara",
    league: "Liiga",
    conference: "Finland",
    category: "Liiga Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 71,
    height_str: "5'11\"",
    weight_lbs: 181,
    hometown: "Ylöjärvi, Finland",
    date_of_birth: "2006-05-11",
    previous_team: "Jukurit (Liiga)",
    draft_status: "Buffalo (2024, 14th)",
    country: "FIN",
    composite_score: 95.2,
    avatar_gradient: "from-blue-600 to-orange-600",
    notes: "Visionary playmaker with premier Hockey IQ. Logged top-line minutes as a 17-year-old against men in Liiga.",
    combine: { flying_30m_sec: 3.47, broad_jump_in: 113, pro_agility_5_10_5_sec: 4.09, grip_strength_lbs: 166, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 91.0, controlled_exit_pct: 92.5, faceoff_win_pct: 54.0, high_danger_pass_comp_pct: 91.5, shoulder_scans_per_possession: 8.8, wall_battle_win_pct: 89.0 },
    skill_rubric: { edges: 93, puck_skills: 95, shooting: 89, hockey_iq: 98, contact: 86, d_zone: 92, transition: 94, goalie: 0 }
  },
  {
    id: "ovs_007",
    entity_type: "player",
    name: "Emil Hemming",
    num: 72,
    pos: "F",
    role_title: "Sniper / Power Forward",
    team: "TPS Turku",
    institution: "TPS Turku",
    league: "Liiga",
    conference: "Finland",
    category: "Liiga Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 73,
    height_str: "6'1\"",
    weight_lbs: 205,
    hometown: "Vaasa, Finland",
    date_of_birth: "2006-06-27",
    previous_team: "TPS U20",
    draft_status: "Dallas (2024, 29th)",
    country: "FIN",
    composite_score: 92.9,
    avatar_gradient: "from-slate-700 to-black",
    notes: "Lethal one-timer release from the left circle. Heavy frame that wins contested slot battles and generates rebounds.",
    combine: { flying_30m_sec: 3.48, broad_jump_in: 115, pro_agility_5_10_5_sec: 4.14, grip_strength_lbs: 175, rotational_medball_mph: 53.0 },
    micro_kpis: { controlled_entry_pct: 86.5, controlled_exit_pct: 88.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 82.0, shoulder_scans_per_possession: 6.7, wall_battle_win_pct: 92.0 },
    skill_rubric: { edges: 89, puck_skills: 90, shooting: 97, hockey_iq: 91, contact: 93, d_zone: 88, transition: 89, goalie: 0 }
  },
  {
    id: "ovs_008",
    entity_type: "player",
    name: "Aron Kiviharju",
    num: 78,
    pos: "D",
    role_title: "Puck-Moving Defenseman",
    team: "HIFK",
    institution: "HIFK",
    league: "Liiga",
    conference: "Finland",
    category: "Liiga Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 70,
    height_str: "5'10\"",
    weight_lbs: 172,
    hometown: "Esbjerg, Denmark",
    date_of_birth: "2006-01-25",
    previous_team: "TPS Turku",
    draft_status: "Minnesota (2024, 122nd)",
    country: "FIN",
    composite_score: 91.5,
    avatar_gradient: "from-red-700 to-blue-900",
    notes: "Generational passing vision and blue-line quarterbacking. Recovered from injury to anchor HIFK's power play.",
    combine: { flying_30m_sec: 3.51, broad_jump_in: 110, pro_agility_5_10_5_sec: 4.12, grip_strength_lbs: 158, rotational_medball_mph: 49.0 },
    micro_kpis: { controlled_entry_pct: 90.0, controlled_exit_pct: 96.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 94.0, shoulder_scans_per_possession: 9.1, wall_battle_win_pct: 81.0 },
    skill_rubric: { edges: 94, puck_skills: 94, shooting: 84, hockey_iq: 98, contact: 78, d_zone: 86, transition: 96, goalie: 0 }
  },

  // Switzerland (National League)
  {
    id: "ovs_009",
    entity_type: "player",
    name: "Leon Muggli",
    num: 17,
    pos: "D",
    role_title: "Two-Way Defenseman",
    team: "EV Zug",
    institution: "EV Zug",
    league: "National League (NL)",
    conference: "Switzerland",
    category: "NL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 73,
    height_str: "6'1\"",
    weight_lbs: 179,
    hometown: "Cham, Switzerland",
    date_of_birth: "2006-07-09",
    previous_team: "EVZ Academy",
    draft_status: "Washington (2024, 52nd)",
    country: "SUI",
    composite_score: 92.4,
    avatar_gradient: "from-blue-700 to-cyan-600",
    notes: "Remarkably poised teenage blueliner in Switzerland's top professional league. Clean first passes and active stick checking.",
    combine: { flying_30m_sec: 3.47, broad_jump_in: 114, pro_agility_5_10_5_sec: 4.11, grip_strength_lbs: 164, rotational_medball_mph: 50.0 },
    micro_kpis: { controlled_entry_pct: 88.0, controlled_exit_pct: 93.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 87.0, shoulder_scans_per_possession: 7.7, wall_battle_win_pct: 88.0 },
    skill_rubric: { edges: 92, puck_skills: 89, shooting: 85, hockey_iq: 94, contact: 86, d_zone: 92, transition: 93, goalie: 0 }
  },
  {
    id: "ovs_010",
    entity_type: "player",
    name: "Denis Malgin",
    num: 62,
    pos: "F",
    role_title: "Dynamic Playmaker",
    team: "ZSC Lions",
    institution: "ZSC Lions",
    league: "National League (NL)",
    conference: "Switzerland",
    category: "NL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 69,
    height_str: "5'9\"",
    weight_lbs: 176,
    hometown: "Olten, Switzerland",
    date_of_birth: "1997-01-18",
    previous_team: "Colorado Avalanche / Toronto Maple Leafs",
    draft_status: "Florida (2015, 102nd)",
    country: "SUI",
    composite_score: 94.1,
    avatar_gradient: "from-blue-900 to-red-600",
    notes: "Premier European playmaker with exceptional agility, dynamic stickhandling in tight areas, and Swiss National Team pedigree.",
    combine: { flying_30m_sec: 3.40, broad_jump_in: 120, pro_agility_5_10_5_sec: 3.98, grip_strength_lbs: 170, rotational_medball_mph: 52.0 },
    micro_kpis: { controlled_entry_pct: 94.0, controlled_exit_pct: 92.0, faceoff_win_pct: 53.0, high_danger_pass_comp_pct: 92.0, shoulder_scans_per_possession: 8.5, wall_battle_win_pct: 86.0 },
    skill_rubric: { edges: 97, puck_skills: 96, shooting: 90, hockey_iq: 96, contact: 81, d_zone: 88, transition: 97, goalie: 0 }
  },

  // Czechia (Tipsport Extraliga)
  {
    id: "ovs_011",
    entity_type: "player",
    name: "Adam Jiříček",
    num: 5,
    pos: "D",
    role_title: "Mobile Two-Way Defenseman",
    team: "HC Škoda Plzeň",
    institution: "HC Škoda Plzeň",
    league: "Tipsport Extraliga",
    conference: "Czech Republic",
    category: "Extraliga Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 74,
    height_str: "6'2\"",
    weight_lbs: 182,
    hometown: "Klatovy, Czech Republic",
    date_of_birth: "2006-06-28",
    previous_team: "HC Plzeň U20",
    draft_status: "St. Louis (2024, 16th)",
    country: "CZE",
    composite_score: 94.0,
    avatar_gradient: "from-blue-700 to-indigo-900",
    notes: "Brother of David Jiříček. Outstanding hockey instincts, aggressive gap control, and deceptive breakout capability.",
    combine: { flying_30m_sec: 3.45, broad_jump_in: 116, pro_agility_5_10_5_sec: 4.10, grip_strength_lbs: 172, rotational_medball_mph: 52.5 },
    micro_kpis: { controlled_entry_pct: 89.0, controlled_exit_pct: 94.5, faceoff_win_pct: 0, high_danger_pass_comp_pct: 88.0, shoulder_scans_per_possession: 7.8, wall_battle_win_pct: 90.0 },
    skill_rubric: { edges: 93, puck_skills: 91, shooting: 88, hockey_iq: 95, contact: 90, d_zone: 93, transition: 94, goalie: 0 }
  },
  {
    id: "ovs_012",
    entity_type: "player",
    name: "Tomáš Galvas",
    num: 12,
    pos: "D",
    role_title: "Puck Mover",
    team: "Bílí Tygři Liberec",
    institution: "Bílí Tygři Liberec",
    league: "Tipsport Extraliga",
    conference: "Czech Republic",
    category: "Extraliga Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 70,
    height_str: "5'10\"",
    weight_lbs: 154,
    hometown: "Brno, Czech Republic",
    date_of_birth: "2006-02-11",
    previous_team: "HC Olomouc U20",
    draft_status: "Eligible 2026",
    country: "CZE",
    composite_score: 91.2,
    avatar_gradient: "from-sky-600 to-blue-800",
    notes: "Sublime skater with elite transitional agility and fast transition puck movement.",
    combine: { flying_30m_sec: 3.41, broad_jump_in: 115, pro_agility_5_10_5_sec: 4.02, grip_strength_lbs: 152, rotational_medball_mph: 48.0 },
    micro_kpis: { controlled_entry_pct: 91.0, controlled_exit_pct: 95.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 90.0, shoulder_scans_per_possession: 8.3, wall_battle_win_pct: 79.0 },
    skill_rubric: { edges: 96, puck_skills: 92, shooting: 82, hockey_iq: 93, contact: 76, d_zone: 85, transition: 97, goalie: 0 }
  },

  // Germany (DEL)
  {
    id: "ovs_013",
    entity_type: "player",
    name: "Leonhard Pföderl",
    num: 93,
    pos: "F",
    role_title: "Goal Scorer",
    team: "Eisbären Berlin",
    institution: "Eisbären Berlin",
    league: "DEL (Deutsche Eishockey Liga)",
    conference: "Germany",
    category: "DEL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 192,
    hometown: "Bad Tölz, Germany",
    date_of_birth: "1993-09-01",
    previous_team: "Thomas Sabo Ice Tigers",
    draft_status: "Undrafted Free Agent",
    country: "GER",
    composite_score: 93.5,
    avatar_gradient: "from-blue-800 to-red-700",
    notes: "Olympic silver medalist and premier DEL goal scorer. Clinical release around the crease and intelligent off-puck positioning.",
    combine: { flying_30m_sec: 3.50, broad_jump_in: 112, pro_agility_5_10_5_sec: 4.15, grip_strength_lbs: 176, rotational_medball_mph: 52.0 },
    micro_kpis: { controlled_entry_pct: 87.0, controlled_exit_pct: 88.0, faceoff_win_pct: 51.0, high_danger_pass_comp_pct: 85.0, shoulder_scans_per_possession: 7.2, wall_battle_win_pct: 90.0 },
    skill_rubric: { edges: 90, puck_skills: 92, shooting: 96, hockey_iq: 95, contact: 88, d_zone: 89, transition: 88, goalie: 0 }
  },

  // Europe / KHL Elite Prospects
  {
    id: "ovs_014",
    entity_type: "player",
    name: "Ivan Demidov",
    num: 11,
    pos: "F",
    role_title: "Superstar Winger",
    team: "SKA Saint Petersburg",
    institution: "SKA Saint Petersburg",
    league: "KHL",
    conference: "Russia",
    category: "KHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 192,
    hometown: "Sergiyev Posad, Russia",
    date_of_birth: "2005-12-10",
    previous_team: "SKA-1946 (MHL)",
    draft_status: "Montreal (2024, 5th)",
    country: "RUS",
    composite_score: 98.4,
    avatar_gradient: "from-blue-700 to-red-600",
    notes: "Top-tier dynamic offensive weapon. Unbelievable edge control, 1-on-1 deception, and generational vision inside the blue line.",
    combine: { flying_30m_sec: 3.38, broad_jump_in: 122, pro_agility_5_10_5_sec: 3.96, grip_strength_lbs: 174, rotational_medball_mph: 54.0 },
    micro_kpis: { controlled_entry_pct: 96.5, controlled_exit_pct: 94.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 95.0, shoulder_scans_per_possession: 9.4, wall_battle_win_pct: 91.0 },
    skill_rubric: { edges: 99, puck_skills: 99, shooting: 96, hockey_iq: 98, contact: 85, d_zone: 88, transition: 99, goalie: 0 }
  },
  {
    id: "ovs_015",
    entity_type: "player",
    name: "Anton Silayev",
    num: 21,
    pos: "D",
    role_title: "Towering Two-Way Defenseman",
    team: "Torpedo Nizhny Novgorod",
    institution: "Torpedo Nizhny Novgorod",
    league: "KHL",
    conference: "Russia",
    category: "KHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 79,
    height_str: "6'7\"",
    weight_lbs: 211,
    hometown: "Sarov, Russia",
    date_of_birth: "2006-04-11",
    previous_team: "Chaika Nizhny Novgorod",
    draft_status: "New Jersey (2024, 10th)",
    country: "RUS",
    composite_score: 96.1,
    avatar_gradient: "from-blue-900 to-cyan-700",
    notes: "Rare 6'7\" skater with fluid stride, punishing wingspan, and modern puck-distribution under pressure in the KHL.",
    combine: { flying_30m_sec: 3.44, broad_jump_in: 120, pro_agility_5_10_5_sec: 4.10, grip_strength_lbs: 192, rotational_medball_mph: 56.0 },
    micro_kpis: { controlled_entry_pct: 84.0, controlled_exit_pct: 94.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 88.0, shoulder_scans_per_possession: 7.9, wall_battle_win_pct: 98.0 },
    skill_rubric: { edges: 94, puck_skills: 91, shooting: 89, hockey_iq: 95, contact: 99, d_zone: 98, transition: 93, goalie: 0 }
  },

  // United Kingdom (EIHL)
  {
    id: "ovs_016",
    entity_type: "player",
    name: "Scott Conway",
    num: 10,
    pos: "C",
    role_title: "Dynamic Scoring Center",
    team: "Belfast Giants",
    institution: "Belfast Giants",
    league: "EIHL (Elite Ice Hockey League)",
    conference: "United Kingdom",
    category: "EIHL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 185,
    hometown: "Basingstoke, United Kingdom",
    date_of_birth: "1995-04-09",
    previous_team: "Providence Friars (NCAA D1)",
    draft_status: "Undrafted Free Agent",
    country: "GBR",
    composite_score: 92.1,
    avatar_gradient: "from-teal-600 to-indigo-900",
    notes: "Former NCAA D1 standout turned EIHL scoring champion. Outstanding pace, net drive, and leadership for the Belfast Giants.",
    combine: { flying_30m_sec: 3.46, broad_jump_in: 114, pro_agility_5_10_5_sec: 4.12, grip_strength_lbs: 170, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 90.0, controlled_exit_pct: 91.0, faceoff_win_pct: 56.5, high_danger_pass_comp_pct: 88.0, shoulder_scans_per_possession: 7.6, wall_battle_win_pct: 89.0 },
    skill_rubric: { edges: 92, puck_skills: 93, shooting: 94, hockey_iq: 93, contact: 88, d_zone: 89, transition: 92, goalie: 0 }
  },

  // Asia League Ice Hockey
  {
    id: "ovs_017",
    entity_type: "player",
    name: "Shogo Nakajima",
    num: 18,
    pos: "F",
    role_title: "Center / Playmaker",
    team: "Red Eagles Hokkaido",
    institution: "Red Eagles Hokkaido",
    league: "Asia League Ice Hockey",
    conference: "Japan",
    category: "Asia League Pro",
    class_level: "Pro Veteran",
    height_in: 70,
    height_str: "5'10\"",
    weight_lbs: 174,
    hometown: "Kushiro, Japan",
    date_of_birth: "1993-09-24",
    previous_team: "Chuo University",
    draft_status: "Undrafted Free Agent",
    country: "JPN",
    composite_score: 90.8,
    avatar_gradient: "from-red-600 to-neutral-900",
    notes: "Japanese national team captain. Exceptional skating cadence, low center of gravity, and disciplined positional responsibility.",
    combine: { flying_30m_sec: 3.42, broad_jump_in: 116, pro_agility_5_10_5_sec: 4.04, grip_strength_lbs: 162, rotational_medball_mph: 49.5 },
    micro_kpis: { controlled_entry_pct: 89.0, controlled_exit_pct: 92.0, faceoff_win_pct: 54.0, high_danger_pass_comp_pct: 89.0, shoulder_scans_per_possession: 8.0, wall_battle_win_pct: 84.0 },
    skill_rubric: { edges: 95, puck_skills: 91, shooting: 88, hockey_iq: 94, contact: 82, d_zone: 91, transition: 93, goalie: 0 }
  },

  // Australia (AIHL)
  {
    id: "ovs_018",
    entity_type: "player",
    name: "Mackenzie Caruana",
    num: 91,
    pos: "F",
    role_title: "Forward",
    team: "Sydney Bears",
    institution: "Sydney Bears",
    league: "AIHL (Australian Ice Hockey League)",
    conference: "Australia",
    category: "AIHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 185,
    hometown: "Sydney, Australia",
    date_of_birth: "1998-05-14",
    previous_team: "Sydney Bears Junior",
    draft_status: "Undrafted Free Agent",
    country: "AUS",
    composite_score: 88.5,
    avatar_gradient: "from-amber-500 to-slate-900",
    notes: "Top offensive producer in Australia's top national league. Tenacious north-south skater with quick release around the crease.",
    combine: { flying_30m_sec: 3.49, broad_jump_in: 111, pro_agility_5_10_5_sec: 4.14, grip_strength_lbs: 160, rotational_medball_mph: 48.5 },
    micro_kpis: { controlled_entry_pct: 86.0, controlled_exit_pct: 87.0, faceoff_win_pct: 52.0, high_danger_pass_comp_pct: 84.0, shoulder_scans_per_possession: 7.1, wall_battle_win_pct: 88.0 },
    skill_rubric: { edges: 89, puck_skills: 88, shooting: 90, hockey_iq: 89, contact: 88, d_zone: 85, transition: 88, goalie: 0 }
  },

  // Austria (ICEHL)
  {
    id: "ovs_019",
    entity_type: "player",
    name: "Peter Schneider",
    num: 3,
    pos: "F",
    role_title: "Scoring Winger",
    team: "EC Red Bull Salzburg",
    institution: "EC Red Bull Salzburg",
    league: "ICEHL (win2day ICE Hockey League)",
    conference: "Austria",
    category: "ICEHL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 71,
    height_str: "5'11\"",
    weight_lbs: 190,
    hometown: "Klosterneuburg, Austria",
    date_of_birth: "1991-04-04",
    previous_team: "Notre Dame Fighting Irish (NCAA D1) / Vienna Capitals",
    draft_status: "Undrafted Free Agent",
    country: "AUT",
    composite_score: 91.8,
    avatar_gradient: "from-red-600 to-slate-900",
    notes: "Multi-time ICEHL MVP and championship pillar for Red Bull Salzburg. Clinical finisher with high-level European and collegiate pedigree.",
    combine: { flying_30m_sec: 3.47, broad_jump_in: 113, pro_agility_5_10_5_sec: 4.12, grip_strength_lbs: 168, rotational_medball_mph: 51.5 },
    micro_kpis: { controlled_entry_pct: 88.0, controlled_exit_pct: 89.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 86.0, shoulder_scans_per_possession: 7.4, wall_battle_win_pct: 87.0 },
    skill_rubric: { edges: 91, puck_skills: 91, shooting: 94, hockey_iq: 92, contact: 86, d_zone: 87, transition: 90, goalie: 0 }
  },

  // Norway (EliteHockey Ligaen)
  {
    id: "ovs_020",
    entity_type: "player",
    name: "Martin Røymark",
    num: 22,
    pos: "F",
    role_title: "Two-Way Veteran Winger",
    team: "Vålerenga Ishockey",
    institution: "Vålerenga Ishockey",
    league: "EliteHockey Ligaen",
    conference: "Norway",
    category: "EliteHockey Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 73,
    height_str: "6'1\"",
    weight_lbs: 194,
    hometown: "Oslo, Norway",
    date_of_birth: "1986-11-10",
    previous_team: "Färjestad BK / Tappara",
    draft_status: "Undrafted Free Agent",
    country: "NOR",
    composite_score: 89.4,
    avatar_gradient: "from-blue-700 to-red-600",
    notes: "Norwegian National Team icon and Vålerenga captain. Relentless forechecker, defensive zone stalwart, and penalty killing anchor.",
    combine: { flying_30m_sec: 3.52, broad_jump_in: 110, pro_agility_5_10_5_sec: 4.18, grip_strength_lbs: 172, rotational_medball_mph: 50.0 },
    micro_kpis: { controlled_entry_pct: 85.0, controlled_exit_pct: 91.0, faceoff_win_pct: 49.0, high_danger_pass_comp_pct: 83.0, shoulder_scans_per_possession: 7.2, wall_battle_win_pct: 91.0 },
    skill_rubric: { edges: 88, puck_skills: 87, shooting: 87, hockey_iq: 93, contact: 91, d_zone: 94, transition: 87, goalie: 0 }
  },

  // Sweden (HockeyAllsvenskan Tier 2)
  {
    id: "ovs_021",
    entity_type: "player",
    name: "Marcus Krüger",
    num: 16,
    pos: "C",
    role_title: "Two-Way Leadership Center",
    team: "Djurgårdens IF",
    institution: "Djurgårdens IF",
    league: "HockeyAllsvenskan",
    conference: "Sweden",
    category: "HockeyAllsvenskan Tier 2 Pro",
    class_level: "Pro Veteran",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 187,
    hometown: "Stockholm, Sweden",
    date_of_birth: "1990-05-27",
    previous_team: "Chicago Blackhawks / ZSC Lions",
    draft_status: "Chicago (2009, 149th)",
    country: "SWE",
    composite_score: 93.8,
    avatar_gradient: "from-yellow-500 to-blue-800",
    notes: "Two-time Stanley Cup Champion and Olympic medalist returned home to captain Djurgården. Elite defensive faceoff proficiency and veteran leadership.",
    combine: { flying_30m_sec: 3.48, broad_jump_in: 114, pro_agility_5_10_5_sec: 4.10, grip_strength_lbs: 174, rotational_medball_mph: 52.0 },
    micro_kpis: { controlled_entry_pct: 89.0, controlled_exit_pct: 94.0, faceoff_win_pct: 61.5, high_danger_pass_comp_pct: 90.0, shoulder_scans_per_possession: 8.8, wall_battle_win_pct: 92.0 },
    skill_rubric: { edges: 91, puck_skills: 92, shooting: 88, hockey_iq: 98, contact: 90, d_zone: 97, transition: 92, goalie: 0 }
  },

  // Finland (Mestis Tier 2)
  {
    id: "ovs_022",
    entity_type: "player",
    name: "Valtteri Filppula",
    num: 51,
    pos: "C",
    role_title: "Master Playmaker & Leader",
    team: "Jokerit Helsinki",
    institution: "Jokerit Helsinki",
    league: "Mestis",
    conference: "Finland",
    category: "Mestis Tier 2 Pro",
    class_level: "Pro Veteran",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 196,
    hometown: "Vantaa, Finland",
    date_of_birth: "1984-03-20",
    previous_team: "Detroit Red Wings / Genève-Servette HC",
    draft_status: "Detroit (2002, 66th)",
    country: "FIN",
    composite_score: 95.0,
    avatar_gradient: "from-blue-600 to-yellow-500",
    notes: "Triple Gold Club member (Stanley Cup, Olympic Gold, World Championship Gold) returned to captain Jokerit. Masterful puck management and game control.",
    combine: { flying_30m_sec: 3.49, broad_jump_in: 112, pro_agility_5_10_5_sec: 4.12, grip_strength_lbs: 176, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 92.0, controlled_exit_pct: 95.0, faceoff_win_pct: 58.0, high_danger_pass_comp_pct: 94.0, shoulder_scans_per_possession: 9.0, wall_battle_win_pct: 91.0 },
    skill_rubric: { edges: 93, puck_skills: 95, shooting: 90, hockey_iq: 99, contact: 88, d_zone: 95, transition: 94, goalie: 0 }
  },

  // Switzerland (National League)
  {
    id: "ovs_023",
    entity_type: "player",
    name: "Vinzenz Rohrer",
    num: 9,
    pos: "F",
    role_title: "High-Energy Two-Way Winger",
    team: "ZSC Lions",
    institution: "ZSC Lions",
    league: "National League (NL)",
    conference: "Switzerland",
    category: "NL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 70,
    height_str: "5'10\"",
    weight_lbs: 172,
    hometown: "Rankweil, Austria",
    date_of_birth: "2004-09-09",
    previous_team: "Ottawa 67's (OHL)",
    draft_status: "Montreal (2022, 75th)",
    country: "AUT",
    composite_score: 92.5,
    avatar_gradient: "from-red-600 to-blue-900",
    notes: "Energetic Austrian international playing top-line minutes for ZSC Lions. Explosive first steps, relentless puck pursuit, and Swiss NL champion.",
    combine: { flying_30m_sec: 3.41, broad_jump_in: 118, pro_agility_5_10_5_sec: 4.02, grip_strength_lbs: 164, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 89.0, controlled_exit_pct: 91.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 87.0, shoulder_scans_per_possession: 8.1, wall_battle_win_pct: 89.0 },
    skill_rubric: { edges: 94, puck_skills: 91, shooting: 89, hockey_iq: 93, contact: 87, d_zone: 90, transition: 93, goalie: 0 }
  },

  // Germany (DEL)
  {
    id: "ovs_024",
    entity_type: "player",
    name: "Justin Schütz",
    num: 10,
    pos: "F",
    role_title: "Speedy Goal Scorer",
    team: "Adler Mannheim",
    institution: "Adler Mannheim",
    league: "DEL (Deutsche Eishockey Liga)",
    conference: "Germany",
    category: "DEL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 71,
    height_str: "5'11\"",
    weight_lbs: 181,
    hometown: "Kassel, Germany",
    date_of_birth: "2000-06-24",
    previous_team: "Kölner Haie / EHC Red Bull München",
    draft_status: "Florida (2018, 170th)",
    country: "GER",
    composite_score: 92.7,
    avatar_gradient: "from-blue-700 to-red-600",
    notes: "DEL top goalscorer with blazing straight-line acceleration and deceptive snapshot in transition.",
    combine: { flying_30m_sec: 3.39, broad_jump_in: 119, pro_agility_5_10_5_sec: 4.01, grip_strength_lbs: 168, rotational_medball_mph: 52.0 },
    micro_kpis: { controlled_entry_pct: 91.0, controlled_exit_pct: 89.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 85.0, shoulder_scans_per_possession: 7.7, wall_battle_win_pct: 86.0 },
    skill_rubric: { edges: 95, puck_skills: 91, shooting: 96, hockey_iq: 92, contact: 84, d_zone: 86, transition: 94, goalie: 0 }
  },

  // Czechia (Tipsport Extraliga)
  {
    id: "ovs_025",
    entity_type: "player",
    name: "Dominik Lakatoš",
    num: 88,
    pos: "F",
    role_title: "Power Forward & Sniper",
    team: "HC Vítkovice Ridera",
    institution: "HC Vítkovice Ridera",
    league: "Tipsport Extraliga",
    conference: "Czech Republic",
    category: "Extraliga Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 207,
    hometown: "Kolín, Czech Republic",
    date_of_birth: "1997-04-08",
    previous_team: "Bílí Tygři Liberec",
    draft_status: "New York Rangers (2017, 157th)",
    country: "CZE",
    composite_score: 91.9,
    avatar_gradient: "from-blue-800 to-amber-600",
    notes: "Physical force with a booming one-timer from the faceoff circle. Heavy forechecker who creates high-danger second chance opportunities.",
    combine: { flying_30m_sec: 3.51, broad_jump_in: 113, pro_agility_5_10_5_sec: 4.16, grip_strength_lbs: 184, rotational_medball_mph: 54.0 },
    micro_kpis: { controlled_entry_pct: 87.0, controlled_exit_pct: 88.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 84.0, shoulder_scans_per_possession: 7.3, wall_battle_win_pct: 94.0 },
    skill_rubric: { edges: 89, puck_skills: 90, shooting: 95, hockey_iq: 91, contact: 96, d_zone: 88, transition: 89, goalie: 0 }
  },

  // Europe / KHL (SKA)
  {
    id: "ovs_026",
    entity_type: "player",
    name: "Alexander Nikishin",
    num: 57,
    pos: "D",
    role_title: "Dominant Two-Way Defenseman",
    team: "SKA Saint Petersburg",
    institution: "SKA Saint Petersburg",
    league: "KHL",
    conference: "Russia",
    category: "KHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 76,
    height_str: "6'4\"",
    weight_lbs: 216,
    hometown: "Oryol, Russia",
    date_of_birth: "2001-10-02",
    previous_team: "Spartak Moscow",
    draft_status: "Carolina (2020, 69th)",
    country: "RUS",
    composite_score: 97.9,
    avatar_gradient: "from-red-600 to-blue-900",
    notes: "Leading defenseman scorer in the KHL and SKA captain. Crushing open-ice hitting, thunderous point shot, and elite transition game.",
    combine: { flying_30m_sec: 3.42, broad_jump_in: 121, pro_agility_5_10_5_sec: 4.06, grip_strength_lbs: 196, rotational_medball_mph: 57.0 },
    micro_kpis: { controlled_entry_pct: 91.0, controlled_exit_pct: 96.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 92.0, shoulder_scans_per_possession: 8.6, wall_battle_win_pct: 97.0 },
    skill_rubric: { edges: 96, puck_skills: 94, shooting: 97, hockey_iq: 97, contact: 98, d_zone: 96, transition: 97, goalie: 0 }
  },

  // Sweden (SHL - MoDo)
  {
    id: "ovs_027",
    entity_type: "player",
    name: "Lucas Pettersson",
    num: 24,
    pos: "C",
    role_title: "Two-Way Playmaker",
    team: "MoDo Hockey",
    institution: "MoDo Hockey",
    league: "SHL (Swedish Hockey League)",
    conference: "Sweden",
    category: "SHL Tier 1 Pro",
    class_level: "Pro Roster",
    height_in: 72,
    height_str: "6'0\"",
    weight_lbs: 176,
    hometown: "Örnsköldsvik, Sweden",
    date_of_birth: "2006-04-17",
    previous_team: "MoDo Hockey J20",
    draft_status: "Anaheim (2024, 35th)",
    country: "SWE",
    composite_score: 93.1,
    avatar_gradient: "from-red-700 to-emerald-700",
    notes: "Intelligent two-way center with quick processing, defensive responsibility, and crisp distribution in the offensive zone.",
    combine: { flying_30m_sec: 3.44, broad_jump_in: 116, pro_agility_5_10_5_sec: 4.08, grip_strength_lbs: 165, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 89.0, controlled_exit_pct: 93.0, faceoff_win_pct: 54.0, high_danger_pass_comp_pct: 89.0, shoulder_scans_per_possession: 8.2, wall_battle_win_pct: 88.0 },
    skill_rubric: { edges: 93, puck_skills: 93, shooting: 89, hockey_iq: 95, contact: 85, d_zone: 91, transition: 94, goalie: 0 }
  },

  // United Kingdom (EIHL - Sheffield)
  {
    id: "ovs_028",
    entity_type: "player",
    name: "Robert Dowd",
    num: 75,
    pos: "F",
    role_title: "Sniper & Captain",
    team: "Sheffield Steelers",
    institution: "Sheffield Steelers",
    league: "EIHL (Elite Ice Hockey League)",
    conference: "United Kingdom",
    category: "EIHL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 70,
    height_str: "5'10\"",
    weight_lbs: 185,
    hometown: "Billingham, United Kingdom",
    date_of_birth: "1988-05-26",
    previous_team: "Belfast Giants / Great Britain National Team",
    draft_status: "Undrafted Free Agent",
    country: "GBR",
    composite_score: 91.0,
    avatar_gradient: "from-orange-600 to-teal-800",
    notes: "Captain of the Sheffield Steelers and Great Britain National Team. All-time EIHL goal scoring legend with lethal wrist shot.",
    combine: { flying_30m_sec: 3.48, broad_jump_in: 112, pro_agility_5_10_5_sec: 4.14, grip_strength_lbs: 172, rotational_medball_mph: 51.0 },
    micro_kpis: { controlled_entry_pct: 87.0, controlled_exit_pct: 89.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 84.0, shoulder_scans_per_possession: 7.2, wall_battle_win_pct: 88.0 },
    skill_rubric: { edges: 90, puck_skills: 91, shooting: 95, hockey_iq: 92, contact: 88, d_zone: 88, transition: 90, goalie: 0 }
  },

  // Asia League (Japan - Nikko Icebucks)
  {
    id: "ovs_029",
    entity_type: "player",
    name: "Makuru Furuhashi",
    num: 92,
    pos: "F",
    role_title: "High-Pace Scoring Winger",
    team: "HC Tochigi Nikko Icebucks",
    institution: "HC Tochigi Nikko Icebucks",
    league: "Asia League Ice Hockey",
    conference: "Japan",
    category: "Asia League Pro",
    class_level: "Pro Veteran",
    height_in: 69,
    height_str: "5'9\"",
    weight_lbs: 172,
    hometown: "Nikko, Japan",
    date_of_birth: "1993-09-30",
    previous_team: "Chuo University",
    draft_status: "Undrafted Free Agent",
    country: "JPN",
    composite_score: 89.7,
    avatar_gradient: "from-orange-500 to-neutral-900",
    notes: "Top offensive talisman for the Nikko Icebucks and regular Japan National Team scorer with rapid edgework and close-range finishing.",
    combine: { flying_30m_sec: 3.43, broad_jump_in: 114, pro_agility_5_10_5_sec: 4.05, grip_strength_lbs: 160, rotational_medball_mph: 49.0 },
    micro_kpis: { controlled_entry_pct: 88.0, controlled_exit_pct: 90.0, faceoff_win_pct: 50.0, high_danger_pass_comp_pct: 86.0, shoulder_scans_per_possession: 7.8, wall_battle_win_pct: 83.0 },
    skill_rubric: { edges: 93, puck_skills: 90, shooting: 89, hockey_iq: 92, contact: 81, d_zone: 87, transition: 92, goalie: 0 }
  },

  // Australia (AIHL - Newcastle)
  {
    id: "ovs_030",
    entity_type: "player",
    name: "Wehebe Darge",
    num: 88,
    pos: "F",
    role_title: "Power Winger & Playmaker",
    team: "Newcastle Northstars",
    institution: "Newcastle Northstars",
    league: "AIHL (Australian Ice Hockey League)",
    conference: "Australia",
    category: "AIHL Tier 1 Pro",
    class_level: "Pro Veteran",
    height_in: 73,
    height_str: "6'1\"",
    weight_lbs: 198,
    hometown: "Adelaide, Australia",
    date_of_birth: "1991-12-04",
    previous_team: "Adelaide Adrenaline / Australia National Team",
    draft_status: "Undrafted Free Agent",
    country: "AUS",
    composite_score: 88.0,
    avatar_gradient: "from-blue-600 to-amber-500",
    notes: "All-time AIHL scoring star and Australian National Team leader. Physical presence along the boards and high shooting volume.",
    combine: { flying_30m_sec: 3.50, broad_jump_in: 110, pro_agility_5_10_5_sec: 4.18, grip_strength_lbs: 172, rotational_medball_mph: 50.0 },
    micro_kpis: { controlled_entry_pct: 84.0, controlled_exit_pct: 86.0, faceoff_win_pct: 0, high_danger_pass_comp_pct: 83.0, shoulder_scans_per_possession: 7.0, wall_battle_win_pct: 90.0 },
    skill_rubric: { edges: 88, puck_skills: 87, shooting: 91, hockey_iq: 89, contact: 92, d_zone: 84, transition: 87, goalie: 0 }
  }
];

// Write static/js/overseas_players_database.js
const playersJsContent = `/**
 * DraftLineup.com - Master Overseas Players & Top European Prospects Database
 * Total Verified Overseas Players: ${OVERSEAS_PROSPECTS.length}
 */

(function(window) {
  'use strict';
  const players = ${JSON.stringify(OVERSEAS_PROSPECTS, null, 2)};
  window.DRAFTLINEUP_OVERSEAS_PLAYERS = players;

  // Auto-merge into window.MASTER_PLAYERS if available
  if (typeof window.MASTER_PLAYERS !== 'undefined' && Array.isArray(window.MASTER_PLAYERS)) {
    players.forEach(p => {
      if (!window.MASTER_PLAYERS.some(existing => existing.id === p.id)) {
        window.MASTER_PLAYERS.push(p);
      }
    });
  }
  if (typeof window.MASTER_NON_PRO_REGISTRY !== 'undefined' && Array.isArray(window.MASTER_NON_PRO_REGISTRY)) {
    players.forEach(p => {
      if (!window.MASTER_NON_PRO_REGISTRY.some(existing => existing.id === p.id)) {
        window.MASTER_NON_PRO_REGISTRY.push(p);
      }
    });
  }
  if (typeof window.SMRP_PLAYERS !== 'undefined' && Array.isArray(window.SMRP_PLAYERS)) {
    players.forEach(p => {
      if (!window.SMRP_PLAYERS.some(existing => existing.id === p.id)) {
        window.SMRP_PLAYERS.push(p);
      }
    });
  }
})(typeof window !== 'undefined' ? window : global);
`;

fs.writeFileSync(path.join(rootDir, 'static', 'js', 'overseas_players_database.js'), playersJsContent, 'utf8');
console.log(`✓ Created overseas_players_database.js with ${OVERSEAS_PROSPECTS.length} premier international prospects.`);

console.log('✓ Successfully completed overseas teams & players database builder.');
